---
# stop the container created before
- name: stop the container created before
  become: yes
  docker_container:
    name: couchdb
    state: absent

- name: Start a container with a couchdb
  become: yes
  docker_container:
    name: couchdb
    image: "{{ couchdb_image }}"
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100-9200:9100-9200"
    volumes:
      - /data
    pull: yes
    env:
      COUCHDB_USER: "{{ couchdb_user }}"
      COUCHDB_PASSWORD: "{{ couchdb_password }}"
      COUCHDB_SECRET: "{{ couchdb_cookie }}"
      ERL_FLAGS: "-setcookie \"{{ couchdb_cookie }}\" -name \"couchdb@{{ inventory_hostname }}\""
