# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: id_grp3
instance_flavor: uom.mse.2c9g
hosts_file_path: ./hosts
ssh_private_key_path: /home/yanbeij/.ssh/id_grp3.pem
github_key_path: /home/yanbeij/.ssh/yanbeij_key
#couchdb_master: 172.26.133.54
couchdb_image: ibmcom/couchdb3:latest
couchdb_user: admin
couchdb_password: admin
couchdb_cookie: 'a192aeb9904e6590849337933b000c99'

# Volume
volumes:
  - vol_name: vol-1
    vol_size: 100
    device: /dev/vdb
    mountpoint: /data
  - vol_name: vol-2
    vol_size: 100
    device: /dev/vdb
    mountpoint: /data
  - vol_name: vol-3
    vol_size: 100
    device: /dev/vdb
    mountpoint: /data
  - vol_name: vol-4
    vol_size: 100
    device: /dev/vdb
    mountpoint: /data

# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb_access
    description: "couchdb_access"
    protocol: tcp
    port_range_min: 1
    port_range_max: 10000
    remote_ip_prefix: 0.0.0.0/0
# Instance
instances:
  - name: instance-1
    volumes: ['vol-1']
  - name: instance-2
    volumes: ['vol-2']
  - name: instance-3
    volumes: ['vol-3']
  - name: instance-4
    volumes: ['vol-4']



