- hosts: all
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: "{{ ssh_private_key_path }}"
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
   - role: common
   - role: git-clone
    - role: mount-volumes
    - role: docker
   - role: wordpress