---
 - name: git pull
   shell: git pull 
   args:
     chdir: /home/ubuntu/COMP90024_Ass2

# - name: Git pull
#   expect:
#     command: git pull https://github.com/Yanbei-Jiang/COMP90024_Ass2.git /home/ubuntu/COMP90024_Ass2
#     responses:
#       Username: Yanbei-Jiang # Username is a regex
#       Password: 990840wp # Password is a regex
# # ---
# - name: pull from git
#   git:
#     repo: https://github.com/Yanbei-Jiang/COMP90024_Ass2.git
#     dest: /home/ubuntu/COMP90024_Ass2
#     update: yes